name: DartsDrill (PROD)

on:
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]
    
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: beta
    - run: flutter config --enable-web
    - run: flutter pub get
    - run: flutter build apk
    - run: flutter build ios --release --no-codesign
    - run: flutter build web
    - uses: actions/upload-artifact@v2
      with:
        name: android
        path: build/app/outputs/flutter-apk/app-release.apk
    - uses: actions/upload-artifact@v2
      with:
        name: ios
        path: Users/runner/work/DartsDrill/DartsDrill/build/ios/iphoneos/Runner.app
    -
        name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: build/web
          repo: astrutz/astrutz.github.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.PAGES_SECRET }}
